# Generated by Django 6.0.2 on 2026-03-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_profile_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.CharField(blank=True, help_text='Enter comma separated labels', max_length=100),
        ),
    ]
